/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_windymelt_voicevoxcore4s_Core */

#ifndef _Included_com_github_windymelt_voicevoxcore4s_Core
#define _Included_com_github_windymelt_voicevoxcore4s_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:      com_github_windymelt_voicevoxcore4s_Core
 * Method:     initialize
 * Signature:  (ZIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_windymelt_voicevoxcore4s_Core_initialize
  (JNIEnv *, jobject, jboolean, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
